const nameList = [
  "Aarav Sharma",
  "Aarushi Patel",
  "Abhay Singh",
  "Abhaya Reddy",
  "Aditi Kumar",
  "Aditya Gupta",
  "Akash Mehta",
  "Akshara Mishra",
  "Alok Verma",
  "Amara Choudhury",
  "Amit Singh",
  "Amrita Iyer",
  "Ananya Agarwal",
  "Anil Kumar",
  "Anjali Sharma",
  "Ankit Patel",
  "Anushka Chauhan",
  "Arjun Gupta",
  "Aruna Singh",
  "Arya Rao",
  "Asha Jain",
  "Ashish Kumar",
  "Avani Sharma",
  "Ayush Patel",
  "Bhavana Reddy",
  "Bhuvan Sharma",
  "Chetan Kumar",
  "Chitra Das",
  "Deepak Singh",
  "Deepika Iyer",
  "Dev Patel",
  "Devi Gupta",
  "Dhruv Sharma",
  "Disha Singh",
  "Divya Reddy",
  "Gaurav Kumar",
  "Gayatri Iyer",
  "Geeta Sharma",
  "Girish Singh",
  "Harini Patel",
  "Harish Kumar",
  "Isha Jain",
  "Ishan Gupta",
  "Ishika Singh",
  "Jagdish Reddy",
  "Jaya Sharma",
  "Jayant Kumar",
  "Jayashree Das",
  "Kavya Singh",
  "Keshav Sharma",
  "Kiran Kumar",
  "Kirti Patel",
  "Lakshmi Gupta",
  "Lalita Singh",
  "Mahesh Kumar",
  "Manisha Sharma",
  "Manoj Singh",
  "Meena Patel",
  "Mohan Kumar",
  "Mohini Singh",
  "Mukesh Sharma",
  "Naina Gupta",
  "Nandini Singh",
  "Naresh Kumar",
  "Neha Patel",
  "Nikhil Singh",
  "Nisha Gupta",
  "Nitin Sharma",
  "Nupur Das",
  "Pallavi Singh",
  "Pankaj Kumar",
  "Parul Sharma",
  "Pradeep Singh",
  "Pragati Patel",
  "Prakash Kumar",
  "Praveen Sharma",
  "Priya Gupta",
  "Rahul Singh",
  "Raj Kumar",
  "Rajan Sharma",
  "Rajesh Singh",
  "Rakesh Kumar",
  "Rama Sharma",
  "Ramesh Singh",
  "Ramya Gupta",
  "Rashmi Patel",
  "Ravi Kumar",
  "Rekha Sharma",
  "Reshma Singh",
  "Rishi Kumar",
  "Rita Gupta",
  "Rohan Singh",
  "Rupa Sharma",
  "Sachin Kumar",
  "Sagar Singh",
  "Sahana Patel",
  "Sameer Sharma",
  "Sanjay Kumar",
  "Sankar Singh",
  "Santosh Sharma",
  "Saraswati Patel",
  "Sarika Sharma",
  "Saroj Singh",
  "Sarvesh Kumar",
  "Satish Sharma",
  "Savita Singh",
  "Seema Gupta",
  "Shalini Sharma",
  "Shanti Patel",
  "Sharad Kumar",
  "Shashi Singh",
  "Sheetal Sharma",
  "Shiv Kumar",
  "Shobha Singh",
  "Shreya Sharma",
  "Shubham Singh",
  "Shyam Kumar",
  "Siddharth Sharma",
  "Sita Patel",
  "Sneha Singh",
  "Sonia Sharma",
  "Sujata Patel",
  "Sunil Kumar",
  "Sunita Sharma",
  "Suraj Singh",
  "Suresh Kumar",
  "Surya Sharma",
  "Swati Singh",
  "Tanuja Patel",
  "Tarun Kumar",
  "Uma Sharma",
  "Usha Singh",
  "Utkarsh Kumar",
  "Vani Sharma",
  "Varun Kumar",
  "Vasu Singh",
  "Veena Sharma",
  "Veer Kumar",
  "Veerendra Singh",
  "Veeresh Kumar",
  "Vidya Sharma",
  "Vijay Kumar",
  "Vijaya Singh",
  "Vikas Sharma",
  "Vikram Singh",
  "Vimal Kumar",
  "Vinay Sharma",
  "Vinod Kumar",
  "Vipin Singh",
  "Vishal Sharma",
  "Vishnu Kumar",
  "Vivek Singh",
  "Yash Sharma",
  "Yogesh Kumar",
  "Abhishek Singh",
  "Advaith Sharma",
  "Aditiya Patel",
  "Aishwarya Singh",
  "Ajay Kumar",
  "Akhil Sharma",
  "Akshay Singh",
  "Alok Kumar",
  "Amey Sharma",
  "Anand Singh",
  "Aniket Kumar",
  "Anil Sharma",
  "Anirudh Singh",
  "Ansh Kumar",
  "Anurag Sharma",
  "Arnav Singh",
  "Arpit Kumar",
  "Arun Sharma",
  "Ashok Singh",
  "Ayush Kumar",
  "Bharat Sharma",
  "Bhavin Singh",
  "Chaitanya Kumar",
  "Darshan Sharma",
  "Gautham Singh",
  "Gautam Sharma",
  "Gurpreet Kumar",
  "Harsh Sharma",
  "Hemanth Singh",
  "Himanshu Sharma",
  "Hrishikesh Singh",
  "Ishaan Kumar",
  "Ishan Sharma",
  "Jaideep Singh",
  "Jay Kumar",
  "Jayesh Sharma",
  "Jignesh Singh",
  "Kaushal Kumar",
  "Ketan Sharma",
  "Kunal Singh",
  "Kush Sharma",
  "Madhav Singh",
  "Mihir Sharma",
  "Milind Kumar",
  "Mohit Singh",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

export function generateRandomSentenceOrPhrase() {
  // Define arrays of words for constructing sentences
  const subjects = [
    "I",
    "You",
    "We",
    "They",
    "He",
    "She",
    "The cat",
    "The dog",
    "The birds",
    "The students",
    "The teacher",
  ];
  const verbs = [
    "am",
    "are",
    "is",
    "was",
    "were",
    "will be",
    "can be",
    "could be",
    "should be",
    "might be",
    "may be",
    "seem",
  ];
  const adjectives = [
    "happy",
    "sad",
    "excited",
    "tired",
    "busy",
    "relaxed",
    "confused",
    "angry",
    "hungry",
    "thirsty",
    "bored",
    "interested",
    "curious",
    "sleepy",
    "anxious",
  ];
  const objects = [
    "today",
    "tomorrow",
    "yesterday",
    "in the morning",
    "in the afternoon",
    "in the evening",
    "at work",
    "at home",
    "on vacation",
    "with friends",
    "with family",
    "at the park",
    "at the beach",
    "in the mountains",
    "in the city",
  ];

  const greetings = [
    "Hello",
    "Hi",
    "Hey",
    "Good morning",
    "Good afternoon",
    "Good evening",
  ];
  const actions = [
    "How are you?",
    "What's up?",
    "How's it going?",
    "What's new?",
    "How's your day?",
  ];
  const responses = [
    "I'm good, thanks!",
    "Not much, just chilling.",
    "It's going well, thanks for asking.",
    "Nothing much, just busy with work.",
    "Pretty good, how about you?",
  ];

  // Randomly decide whether to return a phrase or a sentence
  const isPhrase = Math.random() < 0.5;

  if (isPhrase) {
    // Generate a random phrase by combining random words from each array
    const randomGreeting =
      greetings[Math.floor(Math.random() * greetings.length)];
    const randomAction = actions[Math.floor(Math.random() * actions.length)];
    const randomResponse =
      responses[Math.floor(Math.random() * responses.length)];

    // Construct the final phrase
    const randomPhrase = `${randomGreeting}! ${randomAction} ${randomResponse}`;

    return randomPhrase;
  } else {
    // Generate a random sentence by combining random words from each array
    const randomSubject = subjects[Math.floor(Math.random() * subjects.length)];
    const randomVerb = verbs[Math.floor(Math.random() * verbs.length)];
    const randomAdjective =
      adjectives[Math.floor(Math.random() * adjectives.length)];
    const randomObject = objects[Math.floor(Math.random() * objects.length)];

    // Construct the final sentence
    const randomSentence = `${randomSubject} ${randomVerb} ${randomAdjective} ${randomObject}.`;

    return randomSentence;
  }
}
